name: Deployment

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.2.0
        with:
          github_access_token: ${{ secrets.SECRET_TOKEN }}
          build_configuration: production
          base_href: /openexpenses-web/
          deploy_branch: gh-pages
          build_folder: dist/openexpenses-web
